### ISSUE TITLE
Update abi package

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-sdk#33]
defi-wonderland/solidity-exporter-action was updated to support node 18 https://github.com/defi-wonderland/solidity-exporter-action/issues/47#event-11194174882

1. Publish a new ABI package using `defi-wonderland/solidity-exporter-action`
2. Update the ABI package here.
3. Ensure that app using the SDK can be deployed using node 18
4. Update the SDK in the app and bot

**Comment by jahabeebs** [comment]
@pi0neerpat the interface exporter action has been failing on dev for a while https://github.com/open-dollar/od-contracts/actions/workflows/export-abis.yml

I can either try to 1) run it against main 2) figure out how to get dev stable (yarn install fails, see web3 channel)
