### ISSUE TITLE
Fix proxy-action.ts network routing logic

### ISSUE THREAD

**Issue by jahabeebs** [open-dollar/od-sdk#64]
- We are checking whether to route transactions by checking whether ```this.addressList.GEB_TAX_COLLECTOR !== NULL_ADDRESS``` however, this is preventing us from merging our optimism-hai branch into dev because this logic isn't valid since arbitrum sepolia now has a non null GEB_TAX_COLLECTOR in the latest SDK deployment

1) expose network in the constructor in proxy-actions
2) use network to route transactions

**Comment by pi0neerpat** [comment]
I thought this change was made specifically to enable optimism hai, without causing issues to arb-sepolia. But maybe I didn't implement it correctly?

https://github.com/open-dollar/od-sdk/blame/e728bfe9339b1dd2ca5b33ec25f04c3e236492d1/src/proxy-action.ts#L277

**Comment by jahabeebs** [comment]
> I thought this change was made specifically to enable optimism hai, without causing issues to arb-sepolia. But maybe I didn't implement it correctly?
> 
> https://github.com/open-dollar/od-sdk/blame/e728bfe9339b1dd2ca5b33ec25f04c3e236492d1/src/proxy-action.ts#L277

The problem is both optimism and arbitrum-sepolia have a non-null GEB_TAX_COLLECTOR so at one point one of those networks did not have one and I must have relied on the ```this.addressList.GEB_TAX_COLLECTOR !== NULL_ADDRESS``` logic to stay the same

<img width="740" alt="Screenshot 2024-04-03 at 5 10 22 PM" src="https://github.com/open-dollar/od-sdk/assets/47253537/143e8d17-e987-446b-b1da-fbc48958b52d">

**Comment by jahabeebs** [comment]
@pi0neerpat I fixed the issue in this PR: https://github.com/open-dollar/od-sdk/pull/65

I guess we'll have to update the SDK with the above PR to merge this branch to dev since it includes the faulty routing logic
