### ISSUE TITLE
Testing internal balances

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-sdk#82]
Depends on #80
1. Create a testnet vault
2. use the discord bot /price command to crash the price. 
3. liquidate your vault
4. check internal balance

**Comment by jahabeebs** [comment]
@pi0neerpat I've been having trouble testing this

I liquidated a vault here (I think it was ID 160):
https://sepolia.arbiscan.io/tx/0x39edcbd3df67d7054a28c77579b79154cadd5b28316e3c233c2fb387dbea943b

In the tx logs it says the auction created is auction 1, but when I look in the app I don't see any auctions and I can still see vault 160 in my vault list 

Also, I nuked the price for testnet ARB and got my vault well into liquidation (a 14% collateral ratio) yet it won't let me liquidate via the UI or bot 

https://app.dev.opendollar.com/vaults/175/deposit

**Comment by pi0neerpat** [comment]
Done continued in https://github.com/open-dollar/od-app/issues/634
